kamus_emoji_ke_indonesia = {
    'grinning_face': 'senang',
    'grinning_face_with_big_eyes': 'sangat senang',
    'grinning_face_with_smiling_eyes': 'sangat senang',
    'beaming_face_with_smiling_eyes': 'sangat senang',
    'grinning_squinting_face': 'sangat senang',
    'grinning_face_with_sweat': 'cukup senang',
    'rolling_on_the_floor_laughing': 'sangat senang',
    'face_with_tears_of_joy': 'sangat senang',
    'slightly_smiling_face': 'cukup senang',
    'upside-down_face': 'bingung',
    'melting_face': 'senang',
    'winking_face': 'senang',
    'smiling face with smiling eyes': 'senang',
    'smiling_face_with_halo': 'sangat senang',
    'smiling_face_with_hearts': 'sangat senang',
    'smiling_face_with_heart-eyes': 'sangat senang',
    'star-struck': 'sangat senang',
    'face_blowing_a_kiss': 'sangat senang',
    'kissing_face': 'sangat senang',
    'smiling_face': 'sangat senang',
    'kissing_face_with_closed_eyes': 'sangat senang',
    'kissing_face_with_smiling_eyes': 'sangat senang',
    'smiling_face_with_tear': 'sedih',
    'face_savoring_food': 'lapar',
    'face_with_tongue': 'mengejek',
    'winking_face_with_tongue': 'mengejek',
    'zany_face': 'mengejek',
    'squinting_face_with_tongue': 'penuh semangat',
    'money-mouth_face': 'senang',
    'smiling_face_with_open_hands': 'senang',
    'face_with_hand_over_mouth': 'malu',
    'face_with_open_eyes_and_hand_over_mouth': 'malu',
    'face_with_peeking_eye': 'malu',
    'shushing_face': 'diam',
    'thinking_face': 'bingung',
    'saluting_face': 'siap',
    'zipper-mouth_face': 'netral',
    'zipper-mouth_face': 'skeptis',
    'neutral_face': 'netral',
    'expressionless_face': 'skeptis',
    'face_without_mouth': 'skeptis',
    'dotted_line_face': 'skeptis',
    'face_in_clouds': 'netral',
    'smirking_face': 'mengejek',
    'unamused_face': 'kecewa',
    'face_with_rolling_eyes': 'kecewa',
    'grimacing_face': 'canggung',
    'face_exhaling': 'kecewa',
    'lying_face': 'bohong',
    'relieved_face': 'sedih',
    'pensive_face': 'sedih',
    'sleepy_face': 'mengantuk',
    'drooling_face': 'suka',
    'sleeping_face': 'mengantuk',
    'face_with_medical_mask': 'sakit',
    'face_with_thermometer': 'sakit',
    'face_with_head-bandage': 'sakit',
    'nauseated_face': 'sakit',
    'face_vomiting': 'sakit',
    'sneezing_face': 'sakit',
    'hot_face': 'kepanasan',
    'cold_face': 'kedinginan',
    'woozy_face': 'sakit',
    'face_with_crossed-out_eyes': 'sakit',
    'face_with_spiral_eyes': 'sakit',
    'exploding_head': 'sakit',
    'cowboy_hat_face': 'senang',
    'partying_face': 'sangat senang',
    'disguised_face': 'netral',
    'smiling_face_with_sunglasses': 'bangga',
    'nerd_face': 'netral',
    'face_with_monocle': 'penasaran',
    'confused_face': 'bingung',
    'face_with_diagonal_mouth': 'bingung',
    'worried_face': 'khawatir',
    'slightly_frowning_face': 'sedih',
    'frowning_face': 'sangat sedih',
    'face_with_open_mouth': 'terkejut',
    'hushed_face': 'terkejut',
    'astonished_face': 'terkejut',
    'flushed_face': 'malu',
    'pleading_face': 'berharap',
    'face_holding_back_tears': 'menangis',
    'frowning_face_with_open_mouth': 'sangat sedih',
    'anguished_face': 'sangat sedih',
    'fearful_face': 'takut',
    'anxious_face_with_sweat': 'sangat takut',
    'sad_but_relieved_face': 'takut',
    'crying_face': 'sedih',
    'loudly_crying_face': 'sangat sedih',
    'face_screaming_in_fear': 'sangat takut',
    'confounded_face': 'takut',
    'persevering_face': 'takut',
    'disappointed_face': 'kecewa',
    'downcast_face_with_sweat': 'kecewa',
    'weary_face': 'lelah',
    'tired_face': 'lelah',
    'yawning_face': 'mengantuk',
    'face_with_steam_from_nose': 'marah',
    'pouting_face': 'sangat marah',
    'angry_face': 'marah',
    'face_with_symbols_on_mouth': 'sangat marah',
    'smiling_face_with_horns': 'jahat',
    'angry_face_with_horns': 'sangat marah',
    'skull': 'marah',
    'skull_and_crossbones': 'marah',
    'pile_of_poo': 'kotoran',
    'clown_face': 'badut',
    'ogre': 'monster',
    'goblin': 'monster',
    'ghost': 'hantu',
    'alien': 'monster',
    'alien_monster': 'monster',
    'robot': 'robot',
    'grinning_cat': 'senang',
    'grinning_cat_with_smiling_eyes': 'sangat senang',
    'cat_with_tears_of_joy': 'sangat senang',
    'smiling_cat_with_heart-eyes': 'sangat senang',
    'cat_with_wry_smile': 'cukup senang',
    'kissing_cat': 'senang',
    'weary_cat': 'takut',
    'crying_cat': 'sedih',
    'pouting_cat': 'sangat marah',
    'see-no-evil_monkey': 'bijak',
    'hear-no-evil_monkey': 'bijak',
    'speak-no-evil_monkey': 'bijak',
    'kiss_mark': 'cium',
    'love_letter': 'cinta',
    'heart_with_arrow': 'cinta',
    'heart_with_ribbon': 'cinta',
    'sparkling_heart': 'cinta',
    'growing_heart': 'cinta',
    'beating_heart': 'cinta',
    'revolving_hearts': 'cinta',
    'two_hearts': 'cinta',
    'heart_decoration': 'cinta',
    'heart_exclamation': 'cinta',
    'broken_heart': 'patah hati',
    'heart_on_fire': 'cinta',
    'mending_heart': 'cinta',
    'red_heart': 'cinta',
    'orange_heart': 'cinta',
    'yellow_heart': 'cinta',
    'green_heart': 'cinta',
    'blue_heart': 'cinta',
    'purple_heart': 'cinta',
    'brown_heart': 'cinta',
    'black_heart': 'cinta',
    'white_heart': 'cinta',
    'hundred_points': 'sempurna',
    'anger_symbol': 'marah',
    'collision': 'mantap',
    'dizzy': 'pusing',
    'sweat_droplets': 'keringat',
    'dashing_away': 'pergi',
    'hole': 'lubang',
    'bomb': 'bom',
    'speech_balloon': 'berbicara',
    'eye_in_speech_bubble': 'berbicara',
    'left_speech_bubble': 'berbicara',
    'right_anger_bubble': 'berbicara',
    'thought_balloon': 'berpikir',
    'zzz': 'tidur',
    #
    'waving_hand': 'pergi',
    'raised_back_of_hand': 'pergi',
    'hand_with_fingers_splayed': 'menyapa',
    'raised_hand': 'tunjuk tangan',
    'vulcan_salute': 'menyapa',
    'rightwards_hand': 'menyapa',
    'leftwards_hand': 'menyapa',
    'palm_down_hand': 'memberi',
    'palm_up_hand': 'menerima',
    #
    'OK_hand': 'setuju',
    'pinched_fingers': 'berbicara',
    'pinching_hand': 'sedikit',
    'victory_hand': 'damai',
    'crossed_fingers': 'janji',
    'hand_with_index_finger_and_thumb_crossed': 'cinta',
    'love-you_gesture': 'cinta',
    'sign_of_the_horns': 'menyapa',
    'call_me_hand': 'memanggil',
    #
    'backhand_index_pointing_left': 'menunjuk',
    'backhand_index_pointing_right': 'menunjuk',
    'backhand_index_pointing_up': 'menunjuk',
    'middle_finger': 'memaki',
    'backhand_index_pointing_down': 'menunjuk',
    'index_pointing_up': 'menunjuk',
    'index_pointing_at_the_viewer': 'menunjuk',
    #
    'thumbs_up': 'bagus',
    'thumbs_down': 'jelek',
    'raised_fist': 'kuat ',
    'oncoming_fist': 'kuat ',
    'left-facing_fist': 'kuat ',
    'right-facing_fist': 'kuat ',
    #
    'clapping_hands': 'apresiasi',
    'raising_hands': 'apresiasi',
    'heart_hands': 'cinta',
    'open_hands': 'menerima',
    'palms_up_together': 'berharap',
    'handshake': 'setuju',
    'folded_hands': 'berharap',
    #
    'writing_hand': 'menulis',
    #
    'flexed_biceps': 'kuat ',
    'brain': 'otak',
    # ##
    #
    'person_frowning': 'sedih',
    'man_frowning': 'sedih',
    'woman_frowning': 'sedih',
    'person_pouting': 'marah',
    'man_pouting': 'marah',
    'woman_pouting': 'marah',
    'person_gesturing_NO': 'menolak',
    'man_gesturing_NO': 'menolak',
    'woman_gesturing_NO': 'menolak',
    #
    'person_gesturing_OK': 'setuju',
    'man_gesturing_OK': 'setuju',
    'woman_gesturing_OK': 'setuju',
    'person_tipping_hand': 'bingung',
    'man_tipping_hand': 'bingung',
    'woman_tipping_hand': 'bingung',
    'person_raising_hand': 'bertanya',
    'man_raising_hand': 'bertanya',
    'woman_raising_hand': 'bertanya',
    'deaf_person': 'tuli',
    'deaf_man': 'tuli',
    'deaf_woman': 'tuli',
    #
    # ##
    'person_bowing': 'hormat',
    'man_bowing': 'hormat',
    'woman_bowing': 'hormat',
    'person_facepalming': 'heran',
    'man_facepalming': 'heran',
    'woman_facepalming': 'heran',
    'person_shrugging': 'bingung',
    'man_shrugging': 'bingung',
    'woman_shrugging': 'bingung',
    'person_getting_massage': 'lelah',
    'man_getting_massage': 'lelah',
    'woman_getting_massage': 'lelah',
    #
    'monkey_face': 'monyet',
    'monkey': 'monyet',
    'dog_face': 'anjing',
    'dog': 'anjing',
    'crocodile': 'buaya',
    'turtle': 'kura',
    'snake': 'ular',
    'glass_of_milk': 'susu',
    'hot_beverage': 'minuman panas',
    'teapot': 'teh',
    'wine_glass': 'gelas bir',
    'clinking_beer_mugs': 'setuju',
    'clinking_glasses': 'setuju',
    'fork_and_knife_with_plate': 'makan',
    'new_moon': 'malam',
    'waxing_crescent_moon': 'malam',
    'first_quarter_moon': 'malam',
    'waxing_gibbous_moon': 'malam',
    'full_moon': 'malam',
    'waning_gibbous_moon': 'malam',
    'last_quarter_moon': 'malam',
    'waning_crescent_moon': 'malam',
    'crescent_moon': 'malam',
    'new_moon_face': 'malam',
    'first_quarter_moon_face': 'malam',
    'last_quarter_moon_face': 'malam',
    'thermometer': 'suhu',
    'sun': 'siang',
    'full_moon_face': 'malam',
    'sun_with_face': 'siang',
    'ringed_planet': 'planet',
    'star': 'bintang',
    'glowing_star': 'bintang',
    'shooting_star': 'bintang',
    'milky_way': 'bintang',
    'cloud': 'awan',
    'sun_behind_cloud': 'cerah',
    'cloud_with_lightning_and_rain': 'badai',
    'sun_behind_small_cloud': 'cerah',
    'sun_behind_large_cloud': 'mendung',
    'sun_behind_rain_cloud': 'mendung',
    'cloud_with_rain': 'hujan',
    'cloud_with_snow': 'hujan salju',
    'cloud_with_lightning': 'badai',
    'tornado': 'angin',
    'fog': 'kabut',
    'wind_face': 'angin',
    'cyclone': 'angin',
    'rainbow': 'pelangi',
    'closed_umbrella': 'payung',
    'umbrella': 'payung',
    'umbrella_with_rain_drops': 'hujan',
    'umbrella_on_ground': 'payung',
    'high_voltage': 'petir',
    'snowflake': 'salju',
    'snowman': 'salju',
    'snowman_without_snow': 'salju',
    'comet': 'komet',
    'fire ': 'api',
    'droplet': 'air',
    'water_wave': 'air',
    'jack-o-lantern': 'halloween',
    'Christmas_tree': 'natal',
    'fireworks': 'kembang api',
    'sparkler': 'senang',
    'sparkles': 'senang',
    'party_popper': 'senang',
    'confetti_ball': 'senang',
    'ribbon': 'hadiah',
    'wrapped_gift': 'hadiah',
    'reminder_ribbon': 'hadiah',
    'military_medal': 'juara',
    'trophy': 'juara',
    'sports_medal': 'juara',
    '1st_place_medal': 'juara',
    '2nd_place_medal': 'juara',
    '3rd_place_medal': 'juara',
    'soccer_ball': 'sepak bola',
    'basketball': 'basket',
    'badminton': 'badminton',
    'bullseye': 'target',
    'video_game': 'permainan',
    'joystick': 'permainan ',
    'game_die': 'permainan dadu',
    'artist_palette': 'gambar',
    'money_bag': 'permainan dadu',
    'coin': 'uang',
    'dollar_banknote': 'uang',
    'money_with_wings': 'uang',
    'credit_card': 'uang',
    #
    #
    # 'waving_hand': 'pergi',
    # 'raised_back_of_hand': 'pergi',
    # 'hand_with_fingers_splayed': 'menyapa',
    # 'raised_hand': 'tunjuk tangan',
    # 'vulcan_salute': 'menyapa',
    # 'rightwards_hand': 'menyapa',
    # 'leftwards_hand': 'meyapa',
    # 'palm_down_hand': 'mengambil',
    # 'palm_up_hand': 'menerima',
    #
    'waving_hand_light_skin_tone': 'pergi',
    'waving_hand_medium-light_skin_tone': 'pergi',
    'waving_hand_medium_skin_tone': 'pergi',
    'waving_hand_medium-dark_skin_tone': 'pergi',
    'waving_hand_dark_skin_tone': 'pergi',
    # ----------
    'raised_back_of_hand_light_skin_tone': 'pergi',
    'raised_back_of_hand_medium-light_skin_tone': 'pergi',
    'raised_back_of_hand_medium_skin_tone': 'pergi',
    'raised_back_of_hand_medium-dark_skin_tone': 'pergi',
    'raised_back_of_hand_dark_skin_tone': 'pergi',
    # ----------
    'hand_with_fingers_splayed_light_skin_tone': 'menyapa',
    'hand_with_fingers_splayed_medium-light_skin_tone': 'menyapa',
    'hand_with_fingers_splayed_medium_skin_tone': 'menyapa',
    'hand_with_fingers_splayed_medium-dark_skin_tone': 'menyapa',
    'hand_with_fingers_splayed_dark_skin_tone': 'menyapa',
    # ----------
    'raised_hand_light_skin_tone': 'tunjuk tangan',
    'raised_hand_medium-light_skin_tone': 'tunjuk tangan',
    'raised_hand_medium_skin_tone': 'tunjuk tangan',
    'raised_hand_medium-dark_skin_tone': 'tunjuk tangan',
    'raised_hand_dark_skin_tone': 'tunjuk tangan',
    # ----------
    'vulcan_salute_light_skin_tone': 'menyapa',
    'vulcan_salute_medium-light_skin_tone': 'menyapa',
    'vulcan_salute_medium_skin_tone': 'menyapa',
    'vulcan_salute_medium-dark_skin_tone': 'menyapa',
    'vulcan_salute_dark_skin_tone': 'menyapa',
    # ----------
    'rightwards_hand_light_skin_tone': 'menyapa',
    'rightwards_hand_medium-light_skin_tone': 'menyapa',
    'rightwards_hand_medium_skin_tone': 'menyapa',
    'rightwards_hand_medium-dark_skin_tone': 'menyapa',
    'rightwards_hand_dark_skin_tone': 'menyapa',
    # ----------
    'leftwards_hand_light_skin_tone': 'menyapa',
    'leftwards_hand_medium-light_skin_tone': 'menyapa',
    'leftwards_hand_medium_skin_tone': 'menyapa',
    'leftwards_hand_medium-dark_skin_tone': 'menyapa',
    'leftwards_hand_dark_skin_tone': 'menyapa',
    # ----------
    'palm_down_hand_light_skin_tone': 'memberi',
    'palm_down_hand_medium-light_skin_tone': 'memberi',
    'palm_down_hand_medium_skin_tone': 'memberi',
    'palm_down_hand_medium-dark_skin_tone': 'memberi',
    'palm_down_hand_dark_skin_tone': 'memberi',
    # ----------
    'palm_up_hand_light_skin_tone': 'menerima',
    'palm_up_hand_medium-light_skin_tone': 'menerima',
    'palm_up_hand_medium_skin_tone': 'menerima',
    'palm_up_hand_medium-dark_skin_tone': 'menerima',
    'palm_up_hand_dark_skin_tone': 'menerima',
    # ----------
    #
    # 'OK_hand': 'setuju',
    # 'pinched_fingers': 'gestur',
    # 'pinching_hand': 'gestur',
    # 'victory_hand': 'damai',
    # 'crossed_fingers': 'janji',
    # 'hand_with_index_finger_and_thumb_crossed': 'cinta',
    # 'love-you_gesture': 'cinta',
    # 'sign_of_the_horns': 'menyapa',
    # 'call_me_hand': 'memanggil',
    #
    'OK_hand_light_skin_tone': 'setuju',
    'OK_hand_medium-light_skin_tone': 'setuju',
    'OK_hand_medium_skin_tone': 'setuju',
    'OK_hand_medium-dark_skin_tone': 'setuju',
    'OK_hand_dark_skin_tone': 'setuju',
    # ----------
    'pinched_fingers_light_skin_tone': 'berbicara',
    'pinched_fingers_medium-light_skin_tone': 'berbicara',
    'pinched_fingers_medium_skin_tone': 'berbicara',
    'pinched_fingers_medium-dark_skin_tone': 'berbicara',
    'pinched_fingers_dark_skin_tone': 'berbicara',
    # ----------
    'pinching_hand_light_skin_tone': 'sedikit',
    'pinching_hand_medium-light_skin_tone': 'sedikit',
    'pinching_hand_medium_skin_tone': 'sedikit',
    'pinching_hand_medium-dark_skin_tone': 'sedikit',
    'pinching_hand_dark_skin_tone': 'sedikit',
    # ----------
    'victory_hand_light_skin_tone': 'damai',
    'victory_hand_medium-light_skin_tone': 'damai',
    'victory_hand_medium_skin_tone': 'damai',
    'victory_hand_medium-dark_skin_tone': 'damai',
    'victory_hand_dark_skin_tone': 'damai',
    # ----------
    'crossed_fingers_light_skin_tone': 'janji',
    'crossed_fingers_medium-light_skin_tone': 'janji',
    'crossed_fingers_medium_skin_tone': 'janji',
    'crossed_fingers_medium-dark_skin_tone': 'janji',
    'crossed_fingers_dark_skin_tone': 'janji',
    # ----------
    'hand_with_index_finger_and_thumb_crossed_light_skin_tone': 'cinta',
    'hand_with_index_finger_and_thumb_crossed_medium-light_skin_tone': 'cinta',
    'hand_with_index_finger_and_thumb_crossed_medium_skin_tone': 'cinta',
    'hand_with_index_finger_and_thumb_crossed_medium-dark_skin_tone': 'cinta',
    'hand_with_index_finger_and_thumb_crossed_dark_skin_tone': 'cinta',
    # ----------
    'love-you_gesture_light_skin_tone': 'cinta',
    'love-you_gesture_medium-light_skin_tone': 'cinta',
    'love-you_gesture_medium_skin_tone': 'cinta',
    'love-you_gesture_medium-dark_skin_tone': 'cinta',
    'love-you_gesture_dark_skin_tone': 'cinta',
    # ----------
    'sign_of_the_horns_light_skin_tone': 'menyapa',
    'sign_of_the_horns_medium-light_skin_tone': 'menyapa',
    'sign_of_the_horns_medium_skin_tone': 'menyapa',
    'sign_of_the_horns_medium-dark_skin_tone': 'menyapa',
    'sign_of_the_horns_dark_skin_tone': 'menyapa',
    # ----------
    'call_me_hand_light_skin_tone': 'memanggil',
    'call_me_hand_medium-light_skin_tone': 'memanggil',
    'call_me_hand_medium_skin_tone': 'memanggil',
    'call_me_hand_medium-dark_skin_tone': 'memanggil',
    'call_me_hand_dark_skin_tone': 'memanggil',
    # ----------
    #
    # 'backhand_index_pointing_left': 'menunjuk',
    # 'backhand_index_pointing_right': 'menunjuk',
    # 'backhand_index_pointing_up': 'menunjuk',
    # 'middle_finger': 'memaki',
    # 'backhand_index_pointing_down': 'menunjuk',
    # 'index_pointing_up': 'menunjuk',
    # 'index_pointing_at_the_viewer': 'menunjuk',
    #
    'backhand_index_pointing_left_light_skin_tone': 'menunjuk',
    'backhand_index_pointing_left_medium-light_skin_tone': 'menunjuk',
    'backhand_index_pointing_left_medium_skin_tone': 'menunjuk',
    'backhand_index_pointing_left_medium-dark_skin_tone': 'menunjuk',
    'backhand_index_pointing_left_dark_skin_tone': 'menunjuk',
    # ----------
    'backhand_index_pointing_right_light_skin_tone': 'menunjuk',
    'backhand_index_pointing_right_medium-light_skin_tone': 'menunjuk',
    'backhand_index_pointing_right_medium_skin_tone': 'menunjuk',
    'backhand_index_pointing_right_medium-dark_skin_tone': 'menunjuk',
    'backhand_index_pointing_right_dark_skin_tone': 'menunjuk',
    # ----------
    'backhand_index_pointing_up_light_skin_tone': 'menunjuk',
    'backhand_index_pointing_up_medium-light_skin_tone': 'menunjuk',
    'backhand_index_pointing_up_medium_skin_tone': 'menunjuk',
    'backhand_index_pointing_up_medium-dark_skin_tone': 'menunjuk',
    'backhand_index_pointing_up_dark_skin_tone': 'menunjuk',
    # ----------
    'middle_finger_light_skin_tone': 'memaki',
    'middle_finger_medium-light_skin_tone': 'memaki',
    'middle_finger_medium_skin_tone': 'memaki',
    'middle_finger_medium-dark_skin_tone': 'memaki',
    'middle_finger_dark_skin_tone': 'memaki',
    # ----------
    'backhand_index_pointing_down_light_skin_tone': 'menunjuk',
    'backhand_index_pointing_down_medium-light_skin_tone': 'menunjuk',
    'backhand_index_pointing_down_medium_skin_tone': 'menunjuk',
    'backhand_index_pointing_down_medium-dark_skin_tone': 'menunjuk',
    'backhand_index_pointing_down_dark_skin_tone': 'menunjuk',
    # ----------
    'index_pointing_up_light_skin_tone': 'setuju',
    'index_pointing_up_medium-light_skin_tone': 'setuju',
    'index_pointing_up_medium_skin_tone': 'setuju',
    'index_pointing_up_medium-dark_skin_tone': 'setuju',
    'index_pointing_up_dark_skin_tone': 'setuju',
    # ----------
    'index_pointing_at_the_viewer_light_skin_tone': 'menunjuk',
    'index_pointing_at_the_viewer_medium-light_skin_tone': 'menunjuk',
    'index_pointing_at_the_viewer_medium_skin_tone': 'menunjuk',
    'index_pointing_at_the_viewer_medium-dark_skin_tone': 'menunjuk',
    'index_pointing_at_the_viewer_dark_skin_tone': 'menunjuk',
    # ----------
    #
    # 'thumbs_up': 'bagus',
    # 'thumbs_down': 'jelek',
    # 'raised_fist': 'kuat ',
    # 'oncoming_fist': 'kuat ',
    # 'left-facing_fist': 'kuat ',
    # 'right-facing_fist': 'kuat ',
    #
    'thumbs_up_light_skin_tone': 'bagus',
    'thumbs_up_medium-light_skin_tone': 'bagus',
    'thumbs_up_medium_skin_tone': 'bagus',
    'thumbs_up_medium-dark_skin_tone': 'bagus',
    'thumbs_up_dark_skin_tone': 'bagus',
    # ----------
    'thumbs_down_light_skin_tone': 'jelek',
    'thumbs_down_medium-light_skin_tone': 'jelek',
    'thumbs_down_medium_skin_tone': 'jelek',
    'thumbs_down_medium-dark_skin_tone': 'jelek',
    'thumbs_down_dark_skin_tone': 'jelek',
    # ----------
    'raised_fist_light_skin_tone': 'kuat',
    'raised_fist_medium-light_skin_tone': 'kuat',
    'raised_fist_medium_skin_tone': 'kuat',
    'raised_fist_medium-dark_skin_tone': 'kuat',
    'raised_fist_dark_skin_tone': 'kuat',
    # ----------
    'oncoming_fist_light_skin_tone': 'kuat',
    'oncoming_fist_medium-light_skin_tone': 'kuat',
    'oncoming_fist_medium_skin_tone': 'kuat',
    'oncoming_fist_medium-dark_skin_tone': 'kuat',
    'oncoming_fist_dark_skin_tone': 'kuat',
    # ----------
    'left-facing_fist_light_skin_tone': 'kuat',
    'left-facing_fist_medium-light_skin_tone': 'kuat',
    'left-facing_fist_medium_skin_tone': 'kuat',
    'left-facing_fist_medium-dark_skin_tone': 'kuat',
    'left-facing_fist_dark_skin_tone': 'kuat',
    # ----------
    'right-facing_fist_light_skin_tone': 'kuat',
    'right-facing_fist_medium-light_skin_tone': 'kuat',
    'right-facing_fist_medium_skin_tone': 'kuat',
    'right-facing_fist_medium-dark_skin_tone': 'kuat',
    'right-facing_fist_dark_skin_tone': 'kuat',
    # ----------
    #
    # 'clapping_hands': 'apresiasi',
    # 'raising_hands': 'apresiasi',
    # 'heart_hands': 'cinta',
    # 'open_hands': 'menerima',
    # 'palms_up_together': 'berharap',
    # 'handshake': 'setuju',
    # 'folded_hands': 'berharap',
    # 'writing_hand': 'menulis',
    #
    'clapping_hands_light_skin_tone': 'apresiasi',
    'clapping_hands_medium-light_skin_tone': 'apresiasi',
    'clapping_hands_medium_skin_tone': 'apresiasi',
    'clapping_hands_medium-dark_skin_tone': 'apresiasi',
    'clapping_hands_dark_skin_tone': 'apresiasi',
    # ----------
    'raising_hands_light_skin_tone': 'apresiasi',
    'raising_hands_medium-light_skin_tone': 'apresiasi',
    'raising_hands_medium_skin_tone': 'apresiasi',
    'raising_hands_medium-dark_skin_tone': 'apresiasi',
    'raising_hands_dark_skin_tone': 'apresiasi',
    # ----------
    'heart_hands_light_skin_tone': 'cinta',
    'heart_hands_medium-light_skin_tone': 'cinta',
    'heart_hands_medium_skin_tone': 'cinta',
    'heart_hands_medium-dark_skin_tone': 'cinta',
    'heart_hands_dark_skin_tone': 'cinta',
    # ----------
    'open_hands_light_skin_tone': 'menerima',
    'open_hands_medium-light_skin_tone': 'menerima',
    'open_hands_medium_skin_tone': 'menerima',
    'open_hands_medium-dark_skin_tone': 'menerima',
    'open_hands_dark_skin_tone': 'menerima',
    # ----------
    'palms_up_together_light_skin_tone': 'berharap',
    'palms_up_together_medium-light_skin_tone': 'berharap',
    'palms_up_together_medium_skin_tone': 'berharap',
    'palms_up_together_medium-dark_skin_tone': 'berharap',
    'palms_up_together_dark_skin_tone': 'berharap',
    # ----------
    'handshake_light_skin_tone': 'setuju',
    'handshake_medium-light_skin_tone': 'setuju',
    'handshake_medium_skin_tone': 'setuju',
    'handshake_medium-dark_skin_tone': 'setuju',
    'handshake_dark_skin_tone': 'setuju',
    # ----------
    'folded_hands_light_skin_tone': 'tolong terimakasih',
    'folded_hands_medium-light_skin_tone': 'tolong terimakasih',
    'folded_hands_medium_skin_tone': 'tolong terimakasih',
    'folded_hands_medium-dark_skin_tone': 'tolong terimakasih',
    'folded_hands_dark_skin_tone': 'tolong terimakasih',
    # ----------
    'writing_hand_light_skin_tone': 'menulis',
    'writing_hand_medium-light_skin_tone': 'menulis',
    'writing_hand_medium_skin_tone': 'menulis',
    'writing_hand_medium-dark_skin_tone': 'menulis',
    'writing_hand_dark_skin_tone': 'menulis',
    # ----------
    #
    # 'flexed_biceps': 'kuat ',
    # 'brain': 'otak',
    #
    'flexed_biceps_light_skin_tone': 'kuat',
    'flexed_biceps_medium-light_skin_tone': 'kuat',
    'flexed_biceps_medium_skin_tone': 'kuat',
    'flexed_biceps_medium-dark_skin_tone': 'kuat',
    'flexed_biceps_dark_skin_tone': 'kuat',
    # ----------
    # ##
    #
    # 'person_frowning': 'sedih',
    # 'man_frowning': 'sedih',
    # 'woman_frowning': 'sedih',
    # 'person_pouting': 'marah',
    # 'man_pouting': 'marah',
    # 'woman_pouting': 'marah',
    # 'person_gesturing_NO': 'menolak',
    # 'man_gesturing_NO': 'menolak',
    # 'woman_gesturing_NO': 'menolak',
    #
    'person_frowning_light_skin_tone': 'sedih',
    'person_frowning_medium-light_skin_tone': 'sedih',
    'person_frowning_medium_skin_tone': 'sedih',
    'person_frowning_medium-dark_skin_tone': 'sedih',
    'person_frowning_dark_skin_tone': 'sedih',
    # ----------
    'man_frowning_light_skin_tone': 'sedih',
    'man_frowning_medium-light_skin_tone': 'sedih',
    'man_frowning_medium_skin_tone': 'sedih',
    'man_frowning_medium-dark_skin_tone': 'sedih',
    'man_frowning_dark_skin_tone': 'sedih',
    # ----------
    'woman_frowning_light_skin_tone': 'sedih',
    'woman_frowning_medium-light_skin_tone': 'sedih',
    'woman_frowning_medium_skin_tone': 'sedih',
    'woman_frowning_medium-dark_skin_tone': 'sedih',
    'woman_frowning_dark_skin_tone': 'sedih',
    # ----------
    'person_pouting_light_skin_tone': 'marah',
    'person_pouting_medium-light_skin_tone': 'marah',
    'person_pouting_medium_skin_tone': 'marah',
    'person_pouting_medium-dark_skin_tone': 'marah',
    'person_pouting_dark_skin_tone': 'marah',
    # ----------
    'man_pouting_light_skin_tone': 'marah',
    'man_pouting_medium-light_skin_tone': 'marah',
    'man_pouting_medium_skin_tone': 'marah',
    'man_pouting_medium-dark_skin_tone': 'marah',
    'man_pouting_dark_skin_tone': 'marah',
    # ----------
    'woman_pouting_light_skin_tone': 'marah',
    'woman_pouting_medium-light_skin_tone': 'marah',
    'woman_pouting_medium_skin_tone': 'marah',
    'woman_pouting_medium-dark_skin_tone': 'marah',
    'woman_pouting_dark_skin_tone': 'marah',
    # ----------
    'person_gesturing_NO_light_skin_tone': 'menolak',
    'person_gesturing_NO_medium-light_skin_tone': 'menolak',
    'person_gesturing_NO_medium_skin_tone': 'menolak',
    'person_gesturing_NO_medium-dark_skin_tone': 'menolak',
    'person_gesturing_NO_dark_skin_tone': 'menolak',
    # ----------
    'man_gesturing_NO_light_skin_tone': 'menolak',
    'man_gesturing_NO_medium-light_skin_tone': 'menolak',
    'man_gesturing_NO_medium_skin_tone': 'menolak',
    'man_gesturing_NO_medium-dark_skin_tone': 'menolak',
    'man_gesturing_NO_dark_skin_tone': 'menolak',
    # ----------
    'woman_gesturing_NO_light_skin_tone': 'menolak',
    'woman_gesturing_NO_medium-light_skin_tone': 'menolak',
    'woman_gesturing_NO_medium_skin_tone': 'menolak',
    'woman_gesturing_NO_medium-dark_skin_tone': 'menolak',
    'woman_gesturing_NO_dark_skin_tone': 'menolak',
    # ----------
    # #
    # 'person_gesturing_OK': 'setuju',
    # 'man_gesturing_OK': 'setuju',
    # 'woman_gesturing_OK': 'setuju',
    # 'person_tipping_hand': 'bingung',
    # 'man_tipping_hand': 'bingung',
    # 'woman_tipping_hand': 'bingung',
    # 'person_raising_hand': 'bertanya',
    # 'man_raising_hand': 'bertanya',
    # 'woman_raising_hand': 'bertanya',
    # 'deaf_person': 'tuli',
    # 'deaf_man': 'tuli',
    # 'deaf_woman': 'tuli',
    #
    'person_gesturing_OK_light_skin_tone': 'setuju',
    'person_gesturing_OK_medium-light_skin_tone': 'setuju',
    'person_gesturing_OK_medium_skin_tone': 'setuju',
    'person_gesturing_OK_medium-dark_skin_tone': 'setuju',
    'person_gesturing_OK_dark_skin_tone': 'setuju',
    # ----------
    'man_gesturing_OK_light_skin_tone': 'setuju',
    'man_gesturing_OK_medium-light_skin_tone': 'setuju',
    'man_gesturing_OK_medium_skin_tone': 'setuju',
    'man_gesturing_OK_medium-dark_skin_tone': 'setuju',
    'man_gesturing_OK_dark_skin_tone': 'setuju',
    # ----------
    'woman_gesturing_OK_light_skin_tone': 'setuju',
    'woman_gesturing_OK_medium-light_skin_tone': 'setuju',
    'woman_gesturing_OK_medium_skin_tone': 'setuju',
    'woman_gesturing_OK_medium-dark_skin_tone': 'setuju',
    'woman_gesturing_OK_dark_skin_tone': 'setuju',
    # ----------
    'person_tipping_hand_light_skin_tone': 'bingung',
    'person_tipping_hand_medium-light_skin_tone': 'bingung',
    'person_tipping_hand_medium_skin_tone': 'bingung',
    'person_tipping_hand_medium-dark_skin_tone': 'bingung',
    'person_tipping_hand_dark_skin_tone': 'bingung',
    # ----------
    'man_tipping_hand_light_skin_tone': 'bingung',
    'man_tipping_hand_medium-light_skin_tone': 'bingung',
    'man_tipping_hand_medium_skin_tone': 'bingung',
    'man_tipping_hand_medium-dark_skin_tone': 'bingung',
    'man_tipping_hand_dark_skin_tone': 'bingung',
    # ----------
    'woman_tipping_hand_light_skin_tone': 'bingung',
    'woman_tipping_hand_medium-light_skin_tone': 'bingung',
    'woman_tipping_hand_medium_skin_tone': 'bingung',
    'woman_tipping_hand_medium-dark_skin_tone': 'bingung',
    'woman_tipping_hand_dark_skin_tone': 'bingung',
    # ----------
    'person_raising_hand_light_skin_tone': 'bertanya',
    'person_raising_hand_medium-light_skin_tone': 'bertanya',
    'person_raising_hand_medium_skin_tone': 'bertanya',
    'person_raising_hand_medium-dark_skin_tone': 'bertanya',
    'person_raising_hand_dark_skin_tone': 'bertanya',
    # ----------
    'man_raising_hand_light_skin_tone': 'bertanya',
    'man_raising_hand_medium-light_skin_tone': 'bertanya',
    'man_raising_hand_medium_skin_tone': 'bertanya',
    'man_raising_hand_medium-dark_skin_tone': 'bertanya',
    'man_raising_hand_dark_skin_tone': 'bertanya',
    # ----------
    'woman_raising_hand_light_skin_tone': 'bertanya',
    'woman_raising_hand_medium-light_skin_tone': 'bertanya',
    'woman_raising_hand_medium_skin_tone': 'bertanya',
    'woman_raising_hand_medium-dark_skin_tone': 'bertanya',
    'woman_raising_hand_dark_skin_tone': 'bertanya',
    # ----------
    'deaf_person_light_skin_tone': 'tuli',
    'deaf_person_medium-light_skin_tone': 'tuli',
    'deaf_person_medium_skin_tone': 'tuli',
    'deaf_person_medium-dark_skin_tone': 'tuli',
    'deaf_person_dark_skin_tone': 'tuli',
    # ----------
    'deaf_man_light_skin_tone': 'tuli',
    'deaf_man_medium-light_skin_tone': 'tuli',
    'deaf_man_medium_skin_tone': 'tuli',
    'deaf_man_medium-dark_skin_tone': 'tuli',
    'deaf_man_dark_skin_tone': 'tuli',
    # ----------
    'deaf_woman_light_skin_tone': 'tuli',
    'deaf_woman_medium-light_skin_tone': 'tuli',
    'deaf_woman_medium_skin_tone': 'tuli',
    'deaf_woman_medium-dark_skin_tone': 'tuli',
    'deaf_woman_dark_skin_tone': 'tuli',
    # ----------
    #
    # 'person_bowing': 'hormat',
    # 'man_bowing': 'hormat',
    # 'woman_bowing': 'hormat',
    # 'person_facepalming': 'heran',
    # 'man_facepalming': 'heran',
    # 'woman_facepalming': 'heran',
    # 'person_shrugging': 'bingung',
    # 'man_shrugging': 'bingung',
    # 'woman_shrugging': 'bingung',
    # 'person_getting_massage': 'lelah',
    # 'man_getting_massage': 'lelah',
    # 'woman_getting_massage': 'lelah',
    #
    'person_bowing_light_skin_tone': 'hormat',
    'person_bowing_medium-light_skin_tone': 'hormat',
    'person_bowing_medium_skin_tone': 'hormat',
    'person_bowing_medium-dark_skin_tone': 'hormat',
    'person_bowing_dark_skin_tone': 'hormat',
    # ----------
    'man_bowing_light_skin_tone': 'hormat',
    'man_bowing_medium-light_skin_tone': 'hormat',
    'man_bowing_medium_skin_tone': 'hormat',
    'man_bowing_medium-dark_skin_tone': 'hormat',
    'man_bowing_dark_skin_tone': 'hormat',
    # ----------
    'woman_bowing_light_skin_tone': 'hormat',
    'woman_bowing_medium-light_skin_tone': 'hormat',
    'woman_bowing_medium_skin_tone': 'hormat',
    'woman_bowing_medium-dark_skin_tone': 'hormat',
    'woman_bowing_dark_skin_tone': 'hormat',
    # ----------
    'person_facepalming_light_skin_tone': 'heran',
    'person_facepalming_medium-light_skin_tone': 'heran',
    'person_facepalming_medium_skin_tone': 'heran',
    'person_facepalming_medium-dark_skin_tone': 'heran',
    'person_facepalming_dark_skin_tone': 'heran',
    # ----------
    'man_facepalming_light_skin_tone': 'heran',
    'man_facepalming_medium-light_skin_tone': 'heran',
    'man_facepalming_medium_skin_tone': 'heran',
    'man_facepalming_medium-dark_skin_tone': 'heran',
    'man_facepalming_dark_skin_tone': 'heran',
    # ----------
    'woman_facepalming_light_skin_tone': 'heran',
    'woman_facepalming_medium-light_skin_tone': 'heran',
    'woman_facepalming_medium_skin_tone': 'heran',
    'woman_facepalming_medium-dark_skin_tone': 'heran',
    'woman_facepalming_dark_skin_tone': 'heran',
    # ----------
    'person_shrugging_light_skin_tone': 'bingung',
    'person_shrugging_medium-light_skin_tone': 'bingung',
    'person_shrugging_medium_skin_tone': 'bingung',
    'person_shrugging_medium-dark_skin_tone': 'bingung',
    'person_shrugging_dark_skin_tone': 'bingung',
    # ----------
    'man_shrugging_light_skin_tone': 'bingung',
    'man_shrugging_medium-light_skin_tone': 'bingung',
    'man_shrugging_medium_skin_tone': 'bingung',
    'man_shrugging_medium-dark_skin_tone': 'bingung',
    'man_shrugging_dark_skin_tone': 'bingung',
    # ----------
    'woman_shrugging_light_skin_tone': 'bingung',
    'woman_shrugging_medium-light_skin_tone': 'bingung',
    'woman_shrugging_medium_skin_tone': 'bingung',
    'woman_shrugging_medium-dark_skin_tone': 'bingung',
    'woman_shrugging_dark_skin_tone': 'bingung',
    # ----------
    'person_getting_massage_light_skin_tone': 'capek',
    'person_getting_massage_medium-light_skin_tone': 'capek',
    'person_getting_massage_medium_skin_tone': 'capek',
    'person_getting_massage_medium-dark_skin_tone': 'capek',
    'person_getting_massage_dark_skin_tone': 'capek',
    # ----------
    'man_getting_massage_light_skin_tone': 'capek',
    'man_getting_massage_medium-light_skin_tone': 'capek',
    'man_getting_massage_medium_skin_tone': 'capek',
    'man_getting_massage_medium-dark_skin_tone': 'capek',
    'man_getting_massage_dark_skin_tone': 'capek',
    # ----------
    'woman_getting_massage_light_skin_tone': 'capek',
    'woman_getting_massage_medium-light_skin_tone': 'capek',
    'woman_getting_massage_medium_skin_tone': 'capek',
    'woman_getting_massage_medium-dark_skin_tone': 'capek',
    'woman_getting_massage_dark_skin_tone': 'capek',
    # ----------
    # ----------

    'woman_dancing_light_skin_tone': 'senang',
    'woman_dancing_medium-light_skin_tone': 'senang',
    'woman_dancing_medium_skin_tone': 'senang',
    'woman_dancing_medium-dark_skin_tone': 'senang',
    'woman_dancing_dark_skin_tone': 'senang',


    # '_light_skin_tone': '',
    # '_medium-light_skin_tone': '',
    # '_medium_skin_tone': '',
    # '_medium-dark_skin_tone': '',
    # '_dark_skin_tone': '',
    # ----------
    # ----------
    'smiling_face_with_smiling_eyes': 'senang',
    ':)': 'miris',
    ':v': 'tertawa',
    ':(': 'sedih',
    ':((': 'sedih',
    ':((': 'sedih',


}

# print(type(kamus_emoji_ke_indonesia))
